### PR TITLE
CC-6773: Abort source task if all columns were not converted correctly.

### PR DESCRIPTION
**Pull request by wicknicks**
Signed-off-by: Arjun Satish <arjun@confluent.io>

### CODE REVIEW

**Comment by wicknicks** [comment]
@levzem good point, we probably do want to use that sort of config but that would need a much bigger change and across all possible area of error. In this PR, I wanted to fix one such bug. For this specific instance, I think we want to discuss if it is ok to silently skip bad records, or throw an exception that kills the task (as we are doing in this PR). IMHO, we should start by throwing exception, and later add the error handling behavior you mention as a feature request.

**Comment by levzem** [comment]
it is probably safer to fail in that case and add it as configurable later. in either case, the log statements need to be updated and then LGTM from me

**Comment by wicknicks** [comment]
@levzem fixed the log messages

**Comment by levzem** [comment]
LGTM

**Pull request merged**
