### PR TITLE
WIP: feat(jdbc): Support specifying default precision and max scale for DE…

### PR DESCRIPTION
**Pull request by justinrlee**
…CIMAL data fields

##### Does this solution apply anywhere else?
- [x] yes
- [ ] no

##### Testing done:
- [ ] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

### CODE REVIEW

**Comment by justinrlee** [comment]
Still need to add tests, and also need to sign the CLA.  But I'm hoping somebody can tell me if this is the right way to address this, or if there's a better way.

**Comment by justinrlee** [comment]
Maybe addresses the item identified here: https://stackoverflow.com/questions/58517842/kafka-connect-jdbc-oracle-number-fields-has-precision-of-64-which-fails-to-rea
and referenced here: https://github.com/confluentinc/kafka-connect-jdbc/issues/563

**Comment by justinrlee** [comment]
[clabot:check]

**Comment by ncliang** [comment]
Thanks for the PR @justinrlee . I am worried that this exposes implementation details to the user that can be hidden in the connector dialect implementation. For instance, one would have to know to configure the max precision and scale to 131072 and 16383 for a numeric that does not have this specified in postgres, based on reading the postgres documentation https://www.postgresql.org/docs/10/datatype-numeric.html#DATATYPE-NUMERIC-TABLE . The same would apply when using other dialects such as Oracle and MS SQL. While I agree with the approach to introduce the change in a backwards-compatible way by disabling it in flags by default, I think we can do a bit more leg work and have the individual database limits applied in their perspective dialects. These changes would go in the Oracle or Postgres dialect implementations with the known limits of the specific dialect, with a high level config option `use.dialect.default.numeric.precision` or similar config added to toggle this behavior on or off. WDYT?

**Comment by justinrlee** [comment]
Closing in favor of https://github.com/confluentinc/kafka-connect-jdbc/pull/1052 (which has been merged) and https://github.com/jcustenborder/kafka-connect-transform-common/pull/75 (pending)

**Pull request closed without merging**
