### PR TITLE
CC-25569: add schema and catalog info to the TableID object

### PR DESCRIPTION
**Pull request by sangeet259**
CC-25569: add schema and catalog info to the TableID object

Raised from base PR. Check here for the discussion - https://github.com/confluentinc/airlock-kafka-connect-jdbc/pull/2

### CODE REVIEW

**Review by Tanish0019 — APPROVED** [review]
@sangeet259 I have approved but can you please check why build is failing?

**Comment by sangeet259** [comment]
Not sure why the build is complaining about 
```
[ERROR] /home/semaphore/kafka-connect-jdbc/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceConnectorConfig.java:415:11: 'method call rparen' has incorrect indentation level 10, expected level should be 12. [Indentation]
```

this file was not touched in this change. Probably updating the pom, changed the xml checkstyle ruleset.

**Comment by sangeet259** [comment]
Tests failing due to junit version discrepancy, will take a look.

**Review by Tanish0019 — APPROVED** [review]
lgtm

**Pull request merged**
