### PR TITLE
MINOR: Remove unused TableRecommender class

### PR DESCRIPTION
**Pull request by C0urante**
Removed in https://github.com/confluentinc/kafka-connect-jdbc/pull/930, accidentally re-introduced in https://github.com/confluentinc/kafka-connect-jdbc/pull/990.

### CODE REVIEW

**Review by aakashnshah — APPROVED** [review]
LGTM, any idea why build fails?

**Comment by C0urante** [comment]
Agh, unused imports. One sec...

**Comment by C0urante** [comment]
Joys of editing via GitHub UI 😎

**Comment by C0urante** [comment]
Jenkins build passed, merging.

**Pull request merged**
