### PR TITLE
Fixes #127. Added delete support for sink. 

### LINKED ISSUE #127: Delete Support for sink
Hello,

In kafka and especially kafka streams a delete is expressed as a null value being published for the specific key that needs to be deleted. I do understand that the current source can't catch deletes as the rows are then gone and wont come up as query results. But the Sink side should probably be able to handle deletes correctly. Especially if you want to store the results of a streams application in a relational database.

Best

### PR DESCRIPTION
**Pull request by andybryant**
A record with null value is considered a delete, much like Kafka Connect.
Deletes are disabled by default. Set config delete.enabled to true to enable. Also requires pk.mode = record_key otherwise it can't find the record to delete.

### CODE REVIEW

**Comment by Analect** [comment]
@ewencp ... would it be possible to have someone review this delete capability?

**Comment by niketanand123** [comment]
Hi Andy,
When do you see this Delete fix going to release? I am not sure why it is the least priority

**Comment by kdrakon** [comment]
*bumping* this...
this feature is desired by a client using the connector

**Comment by niketanand123** [comment]
Hi Kdrakon,
Could you provide the time frame for pushing this to release version?

**Comment by kdrakon** [comment]
@niketanand123 I don't work for Confluent; I'm in the same boat as you - waiting for this to be approved and released.

**Comment by niketanand123** [comment]
@andybryant , Please let me know when can we see your fix going to release version.
We really need the basic operation to work in JDBC sink connector.

**Comment by andybryant** [comment]
@niketanand123  I'm waiting for a review of this. Happy to port to confluent 4.0.0 branch or refactor if needed, but haven't had any feedback yet.

**Comment by andybryant** [comment]
For what it's worth I've been using this code in anger for several months backed by some property based integration tests and haven't seen any issues.

**Comment by gunnarmorling** [comment]
Just came cross this PR and wanted to express that it'd be great to have this feature (haven't looked at the proposed implementation).

It's a common request we see when using the JDBC sink connector with the Debezium CDC connectors, where people would like to get delete events applied, too (We provide an SMT for extracting just the "after" state from Debezium's CDC events, allowing to emit the format expected by this sink connector. Currently that SMT must be configured to [drop any tombstone events](http://debezium.io/docs/configuration/event-flattening/#record_filtering_for_delete_records) in order to work with the JDBC sink).

So we'd be excited to see this implemented!

**Comment by niketanand123** [comment]
@gunnarmorling Could you provide the time frame for pushing this to release version?

**Comment by gunnarmorling** [comment]
@niketanand123, that's a decision left to the Confluent engineers; I just wanted to express that it's a feature welcomed by the community very much.

**Comment by VMarisevs** [comment]
bump...
Hope it will be merged anytime soon!!

**Comment by RanKey1496** [comment]
Waiting for this feature, when this Delete fix going to release?

**Comment by milanogc** [comment]
No answers, what is going on?

**Comment by jakubbujny** [comment]
Any plans for merge?

**Comment by gunnarmorling** [comment]
Btw. for those who run into this when using the Debezium CDC source
connectors, the next 0.9.x release will allow you to add a "deleted" column
into sink records (by means of an SMT). This lets you remove all records
marked as deleted after the fact, e.g. with a batch running on the sink.
Not ideal, but could do the trick until this issue here ist resolved.

**Comment by gunnarmorling** [comment]
> Can you explain how that would be an improvement over the solution presented in this PR?

@ian-axelrod, for sure a fix for this in the JDBC sink connector itself would be more than welcomed. As this feature is something that we've been asked about many times, we figured that for the time being, optionally rewriting DELETEs into an update of a given marker column provides a way to unblock users that wish to replicate deletions (and it also can be used with other sink connectors that can't handle deletes). In addition, working with a rewrite marker column allows you to keep "deleted" records in a sink for some time before deleting them there, too, which might or might no be a useful feature.

I'd suggest to continue this discussion in our Google group if needed, so keep the thread here focused on the proposed change for the JDBC sink connector.

**Comment by RabihHallage** [comment]
are there any plans to merge this PR soon ?

**Comment by ian-axelrod** [comment]
@RabihHallage given that confluent has not paid any attention to this PR, my guess is it will be merged either (1) never or (2) ... never. My team has forked the repo and added delete support to the latest version of the connector. Feel free to use the fork. https://github.com/dailymuse/kafka-connect-jdbc

**Comment by u-phoria** [comment]
I have little doubt Confluent folks are aware of this thread. It has to be one of the "hotter" ones in this project.

It is a non trivial change, so as reluctance to just merge it in is understandable.

However just plain ignoring it is poor form, and doesn't inspire confidence. I hope this changes soon.

**Comment by rhauch** [comment]
I'm hoping to get to this soon to see if this PR can be easily rebased.

**Comment by mcamenzind** [comment]
@rhauch Have any update regarding this PR? Please see @ian-axelrod 's fork, which seems easier to rebase.

**Comment by rhauch** [comment]
@mcamenzind, I started looking into it, but had trouble rebasing and adjusting for the recent changes. I'll take a look at @ian-axelrod's fork -- do you have a link? Is there a PR or just commits on their fork?

**Comment by mcamenzind** [comment]
@rhauch, I squashed the commits on master of [1] back including e7430a3 and rebased it, I think there was exactly one conflict with one documentation file, no issues otherwise. It compiles, I did, however, not get the occasion to test it thoroughly yet. 

There 's no PR, just their fork. To cite @ian-axelrod:
> @RabihHallage given that confluent has not paid any attention to this PR, my guess is it will be merged either (1) never or (2) ... never. My team has forked the repo and added delete support to the latest version of the connector. Feel free to use the fork. https://github.com/dailymuse/kafka-connect-jdbc

I just found this other PR #488 [2], which is based on [1]. You could probably abandon #127 and just rebase and merge  #488. [3] has some comment on the code.

[1] https://github.com/dailymuse/kafka-connect-jdbc/commits/master
[2] https://github.com/confluentinc/kafka-connect-jdbc/pull/488
[3] https://github.com/dailymuse/kafka-connect-jdbc/commit/8ccbe5ea4e194593f31a78c0931880b5f39644e3#r30931000

**Comment by ruggione** [comment]
hi everyone, do you have any news about it?

Thanks in advance

**Comment by marcospassos** [comment]
We are also looking forward to this feature.

**Comment by awebneck** [comment]
Yes, any information on moving this forward? Would really be a handy.

**Comment by RabihHallage** [comment]
guys can any body gives us an ETA or an update about if this feature will be anytime merged ???

**Comment by andybryant** [comment]
Created a new PR against the latest master branch that supports the new `DatabaseDialect` approach. See #641

**Comment by luca-d** [comment]
@gunnarmorling Is the feature of the Debezium CDC source connectors to add a "deleted" column already realised in the current release? I can't find any information on this in the documentation.

**Comment by NathanNam** [comment]
@andybryant would this pr address your request? https://github.com/confluentinc/kafka-connect-jdbc/pull/641

**Pull request closed without merging**
