### PR TITLE
Add support for partition assignment by configuration

### PR DESCRIPTION
**Pull request by clescot**
I have got thousand of databases with the same structure (same schemas and tables).
I needs to regroup the same content (same table names from different databases) in the same Topic, but needs also to isolate content into one partition per database (for an easier data processing).
i will need also to do the same thing from kafka to database (another pull request is on track for sink), to avoid each database client to consume traffic from all other databases.

Remove duplicate content in BulkTableQuerier.java and TimestampIncrementingTableQuerier.java in extractRecord methods :Common code is now present in TableQuerier.java.

implements partition configuration across all topics (check if partition number is not negative and throw a connectException in this case).
add tests on DataConverter (DataConverterTest.java and DataConverterTypesTest.java).
add tests on partitionNumber in TimestampIncrementingTableQuerierTest.java

### CODE REVIEW

**Comment by clescot** [comment]
@shikhar @ewencp What is your feedback about this pull request?
How to sign the Contributor License Agreement?

best regards,
Charles.

**Comment by ewencp** [comment]
ok to test

**Comment by ewencp** [comment]
Sorry @clescot, CLABot was misbhaving. It can be signed here: http://clabot.confluent.io/cla

**Comment by clescot** [comment]
Hi @ewencp , i've signed the CLA.

best regards,
Charles.

**Comment by clescot** [comment]
up?
ping @ewencp 

best regards,

Charles.

**Comment by clescot** [comment]
[clabot:check]

**Comment by clescot** [comment]
Hi,
i close my pull request because my need is to have a different partition assignment for each kafka connect instance (one kafka connect per database) : it can be solved by setting a different key for all messages from kafka connect, by setting a custom key serializer on the producer config.
Charles.

**Pull request closed without merging**
