### PR TITLE
Update for issue #211 - get current timestamp on all DB2 versions

### PR DESCRIPTION
**Pull request by k1th**
Target all product names starting with "DB2" regardless of platform.

### CODE REVIEW

**Comment by k1th** [comment]
[clabot:check]

**Comment by k1th** [comment]
[clabot:check

**Comment by k1th** [comment]
[clabot:check]

**Comment by kkonstantine** [comment]
This PR was closed automatically when the `3.4.0` branch was deleted. Feel free to resubmit on top of `master`

**Comment by k1th** [comment]
@kkonstantine resubmitted as  #308

**Pull request closed without merging**
